name: 'Terraform drift detector'
description: 'detect if drift has occured from our IAC'
inputs:
  TF_VERSION:
    description: 'What terraform version to use'
    default: 0.13.5
  TF_WRAPPER:
    description: 'boolean to deploy wrapper script or not'
    default: false
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.TF_VERSION }}

    - name: Terraform Version
      id: version
      run: terraform version
      shell: bash

    - name: Terraform Init
      id: init
      run: terraform init
      shell: bash

    - name: Terraform Plan
      id: plan
      run: terraform plan -detailed-exitcode
      shell: bash
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      shell: bash
      run: |
        echo "Your IAC is adrift... fix it or fall prey to Davey Jones"
        exit 1

    - run: drift_check.sh
      shell: bash
